name: takein
description: TakeIn fresh local food.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.5.0+474
environment:
  sdk: ">=2.6.0 <3.0.0"
  # Flutter versions prior to 1.12 did not support the
  # flutter.plugin.platforms map.
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: null
  # Should use this: flutter_crashlytics: ^1.0.0
  bmnav: ^0.3.4
  carousel_pro: ^1.0.0
  flutter_rating: ^0.0.2
  google_maps_flutter: ^0.5.28+1
  geolocator: ^5.3.2
  keyboard_visibility: ^0.5.6
  flutter_masked_text: ^0.8.0
  flutter_google_places: ^0.2.1
  #  flutter_calendar: ^0.0.8
  firebase_core: ^0.4.4+3
  firebase_analytics: ^5.0.11
  firebase_crashlytics: ^0.1.3+3
  firebase_messaging: ^6.0.13
  firebase_auth: ^0.16.0
  firebase_remote_config: ^0.3.0+3
  firebase_performance: ^0.3.1+8
  firebase_storage: ^3.1.5
  flutter_facebook_login: ^3.0.0
  sentry: ">=3.0.0 <4.0.0"
  apple_sign_in: ^0.1.0
  toast: ^0.1.5
  flushbar: ^1.10.0
  libphonenumber: ^1.0.1
  dartx: null
  fimber: null
  device_info: ^0.4.2+4
  flutter_crashlytics: ^1.0.0
  wave: ^0.0.8
  line_icons:
    git: https://github.com/galonsos/line_icons.git
  flutter_app_badger: ^1.1.2

  image_picker: ^0.6.1
  http_interceptor: any
  flutter_svg: ^0.18.0

  google_sign_in: ^4.0.11
  cloud_firestore: ^0.13.6

  shared_preferences: ^0.4.2
  http: ^0.12.0+2
  #retry a http call
  retry: ^3.0.0+1
  #flutter_redux: ^0.5.3
  sprintf: "^4.0.2"
  outline_material_icons: ^0.1.1
  switches_kit: null
  rxdart: ^0.23.1

  flutter_webview_plugin: ^0.3.7
  package_info: ^0.4.0+14
  provider: ^4.0.4
  stripe_payment: ^1.0.6
  credit_card_validator: ^0.0.2
  #font_awesome_flutter: ^8.5.0
  connectivity: ^0.4.8+6
  share: ^0.6.2+1
  flutter_swiper: ^1.1.6
  table_calendar: ^2.2.3
  story_view: ^0.11.2

  permission_handler: ^4.3.0
  overlay_support: ^1.0.1
  flutter_markdown: ^0.3.0
  geoflutterfire: ^2.1.0
  flutter_spinkit: ^4.1.0
  #  flutter_app_badger: ^1.1.1
  #video player
  video_player: ^0.10.8+1
  audioplayers: ^0.15.1

  #phone call
  url_launcher: ^5.1.3

  #deep linking
  uni_links: ^0.2.0

  # keyboard_actions:
  keyboard_actions: ^3.3.0+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  #  cached_network_image: ^1.1.3
  cached_network_image: ^2.0.0-rc

  #Offline persistence
  hive: ^1.4.0+1
  hive_flutter: ^0.3.0+1
  path_provider: ^1.6.1

  #http requests testing
  mockito: ^4.1.1
  #extended_image
  extended_image: ^0.7.3-dev
  flutter_screenutil: ^1.0.2
  isolate: ^2.0.3
  image_editor: null
  flusmic: ^0.1.10
  latlong: ^0.6.1
  youtube_player_flutter: ^6.1.0+4
  flutter_xlider: ^3.4.0
  equatable: ^1.1.1
  responsive_builder: ^0.2.0+2
  flare_flutter: ^2.0.6

dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  intl_translation: ^0.17.5
  flutter_driver:
    sdk: flutter
  test: any
  flutter_test:
    sdk: flutter
  #hive_generator: ^0.7.0+2
  build_runner: ^1.7.1

dependency_overrides:
  path: ^1.7.0
  intl: ^0.16.0
  #flutter_markdown: 0.31.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/music/
    - assets/svg/
    - assets/animations/

  fonts:
    - family: icomoon
      fonts:
        - asset: assets/fonts/IcoMoon.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/takein_sym_lg.png"
  image_path_android: "assets/icon/white.png"
  adaptive_icon_background: "#FFFFFF"
